<?php

/**
 * Implements hook_install().
 */
function entityreference_modal_install() {
  // Our hook_menu_alter() implementation should be executed after the one from
  // the entity_translation module. Since the entity_translation module also
  // uses hook_module_implements_alter(), we have to increase our module weight.
  db_update('system')
    ->fields(array('weight' => 12))
    ->condition('name', 'entityreference_modal')
    ->execute();
}
